sonar.organization=snirmal5498
sonar.projectKey=SNirmal5498_CodePulse

sonar.sources=server/src/main/java,client/src
sonar.tests=server/src/test/java,client/src

sonar.java.binaries=server/target/classes

sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,client/src/**/*.test.js,client/src/**/*.test.jsx

sonar.test.inclusions=server/src/test/java/**,client/src/**/*.test.js,client/src/**/*.test.jsxq